# Generated by Django 4.2.5 on 2023-10-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
