# Generated by Django 4.2.5 on 2023-10-07 14:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='stack',
        ),
    ]
