# Generated by Django 4.2.5 on 2023-10-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_cart_stack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stack',
        ),
    ]
