# Generated by Django 4.2.5 on 2023-10-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
